#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
incident-doc v1.0 — 应急响应文档生成器
用法:
  python3 incident-doc.py --interactive  # 问答式生成
  python3 incident-doc.py --yaml inc.yml # 从 YAML 生成
"""
import sys, os, json, datetime

def prompt(label, default=""):
    val = input(f"  {label}: ").strip()
    return val if val else default

def prompt_multi(label):
    print(f"  {label} (每行一条, 空行结束):")
    items = []
    while True:
        l = input("    > ").strip()
        if not l: break
        items.append(l)
    return items

def main():
    if "--yaml" in sys.argv:
        import yaml
        f = sys.argv[sys.argv.index("--yaml")+1]
        d = yaml.safe_load(open(f))
    else:
        print("\n🚨 应急响应文档生成器\n" + "─" * 40)
        print("回答以下问题，自动生成标准复盘文档\n")
        d = {}
        d["title"] = prompt("故障标题 (如: API 502 超过 30 分钟)")
        d["severity"] = prompt("严重级别 SEV1/SEV2/SEV3", "SEV2")
        d["date"] = prompt("日期 (YYYY-MM-DD)", datetime.date.today().isoformat())
        d["start"] = prompt("开始时间 (HH:MM UTC)")
        d["end"] = prompt("结束时间 (HH:MM UTC)")
        d["duration"] = prompt("持续时长", "")
        d["impact_users"] = prompt("影响用户数/比例")
        d["impact_biz"] = prompt("业务影响 (如: 下单失败率 30%)")
        d["services"] = prompt("受影响服务 (逗号分隔)", "")
        d["services"] = [s.strip() for s in d["services"].split(",")] if d["services"] else []
        d["detected_by"] = prompt("如何发现 (监控/用户反馈/巡检)", "监控告警")
        d["detect_delay"] = prompt("发现延迟 (故障发生到发现, 如: 5分钟)", "unknown")
        d["root_cause"] = prompt("根因 (技术原因, 不写人名)")
        d["trigger"] = prompt("触发因素 (什么操作/事件引发的)")
        d["resolution"] = prompt("解决方式 (回滚/扩容/修复)")
        d["timeline"] = prompt_multi("时间线 (格式: HH:MM | 事件 | 谁做的)")
        d["went_well"] = prompt_multi("做得好的地方")
        d["went_wrong"] = prompt_multi("做得不好的地方")
        print("\n  📋 行动项 (每行: 描述 | 负责人 | 优先级P1/P2 | 截止)")
        d["action_items"] = []
        while True:
            l = input("    > ").strip()
            if not l: break
            parts = [x.strip() for x in l.split("|")]
            d["action_items"].append(parts + ["P2", "ASAP"][len(parts):])
        d["author"] = prompt("文档作者", "")

    # 生成 Markdown
    md = f"""# [{d['severity']}] {d['title']}

**Date:** {d['date']} | **Author:** {d.get('author','')} | **Status:** Draft

## Executive Summary

{d['title']}。影响 {d.get('impact_users','未统计')} 用户，{d.get('impact_biz','影响评估中')}。
故障持续 {d.get('duration','unknown')}，通过 {d['resolution']} 解决。

## Impact

- **Users affected:** {d.get('impact_users','unknown')}
- **Business impact:** {d.get('impact_biz','TBD')}
- **Services affected:** {', '.join(d.get('services',[])) or 'TBD'}
- **Detected by:** {d.get('detected_by','monitoring')}
- **Detection delay:** {d.get('detect_delay','unknown')}

## Root Cause

**Technical Root Cause:**
{d.get('root_cause','TBD')}

**Trigger:**
{d.get('trigger','TBD')}

## Timeline

| Time (UTC) | Event | Actor |
|---|---|---|
"""
    for item in d.get("timeline", []):
        parts = [x.strip() for x in item.split("|")]
        while len(parts) < 3: parts.append("")
        md += f"| {parts[0]} | {parts[1]} | {parts[2]} |\n"

    md += "\n## What Went Well\n\n"
    for item in d.get("went_well", []): md += f"- ✅ {item}\n"
    if not d.get("went_well"): md += "- (to be filled in review)\n"

    md += "\n## What Went Poorly\n\n"
    for item in d.get("went_wrong", []): md += f"- ❌ {item}\n"
    if not d.get("went_wrong"): md += "- (to be filled in review)\n"

    md += "\n## Action Items\n\n| # | Action | Owner | Priority | Deadline |\n|---|--------|-------|----------|----------|\n"
    for i, item in enumerate(d.get("action_items", []), 1):
        while len(item) < 4: item.append("P2")
        md += f"| {i} | {item[0]} | {item[1]} | {item[2]} | {item[3]} |\n"
    if not d.get("action_items"):
        md += "| 1 | TBD | TBD | P1 | TBD |\n"

    md += f"\n---\n*Generated by incident-doc v1.0*\n"

    out_file = f"postmortem-{d['date']}-{d['severity'].lower()}.md"
    open(out_file, "w", encoding="utf-8").write(md)
    print(f"\n✅ 文档已生成: {out_file}")

if __name__ == "__main__":
    main()
